POST http://localhost:3000/
content-type: application/json

{
  "title": "abc",
  "date": "09/6/2024",
  "description": "abuble"
}

###

GET http://localhost:3000/0753a857-33ed-48f8-b6ee-811f3704002f
content-type: application/json

###

GET http://localhost:3000/
content-type: application/json
